# Generated by Django 5.1.7 on 2025-04-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
