# Generated by Django 5.1.7 on 2025-04-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app1', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
    ]
