# Generated by Django 5.2 on 2025-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app1', '0003_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mage',
            field=models.ImageField(blank=True, null=True, upload_to='rooms_images/'),
        ),
    ]
