# Generated by Django 5.2 on 2025-04-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS_app1', '0004_room_mage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='mage',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
    ]
